language: php

php:
  - 7.2
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - RUN_TESTS=1
    - CODECOVERAGE=0

services:
  - postgresql
  - mysql

matrix:
  fast_finish: true

  include:

    - php: 7.3
      env: CHECKS=1 RUN_TESTS=0

    - php: 7.3
      env: CODECOVERAGE=1 RUN_TESTS=0

before_install:
  - phpenv config-rm xdebug.ini
  - if [[ $DB = 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

before_script:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --no-interaction; fi
  - if [[ $PREFER_LOWEST = 1 ]]; then composer update --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - if [[ $RUN_TESTS = 1 ]]; then vendor/bin/phpunit; fi

  - if [[ $CODECOVERAGE = 1 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml; fi

  - if [[ $CHECKS = 1 ]]; then composer cs-check; fi
  - if [[ $CHECKS = 1 ]]; then composer stan-setup && composer stan; fi

after_success:
  - if [[ $CODECOVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
