language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - RUN_TESTS=1

matrix:
  fast_finish: true

  include:
    - php: 7.1
      env: RUN_CS=1 RUN_TESTS=0

    - php: 7.1
      env: PHPSTAN=1 RUN_TESTS=0

    - php: 5.6
      env: PREFER_LOWEST=1

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]]; then phpenv config-rm xdebug.ini; fi
  - if [[ -n "$GH_TOKEN" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - if [[ $DB = 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

before_script:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --no-interaction; fi
  - if [[ $PREFER_LOWEST = 1 ]]; then composer update --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - if [[ $RUN_TESTS = 1 && $TRAVIS_PHP_VERSION != 7.1 ]]; then vendor/bin/phpunit; fi
  - if [[ $RUN_TESTS = 1 && $TRAVIS_PHP_VERSION = 7.1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi

  - if [[ $RUN_CS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

  - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.9 && vendor/bin/phpstan analyse -c phpstan.neon -l 4 src; fi

after_success:
  - if [[ $RUN_TESTS = 1 && $TRAVIS_PHP_VERSION = 7.1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
